# -*- coding: utf-8 -*-
"""Deepleaning_vectorization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hs_6efK8EIwDewissPwHRy6nrcgOWjSe
"""

import numpy as np

a= np.array([1,2,3,4])
print(a)

import time

a= np.random.rand(1000000)
b= np.random.rand(1000000)

m = np.array([a,b])
print(m)

tic = time.time()
c= np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version: " + str(1000*(toc-tic)) + "ms")

c=0
tic = time.time()
for i in range(1000000):
  c+=a[i]*b[i]
toc = time.time()
print(c)
print("for loop " + str(1000*(toc-tic)) + "ms")

